# Generated by Django 5.2.12 on 2026-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('game_title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('host_name', models.CharField(max_length=120)),
                ('campus_name', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner friendly'), ('mixed', 'Mixed skill levels'), ('competitive', 'Competitive table')], default='mixed', max_length=20)),
                ('spots_total', models.PositiveIntegerField(default=8)),
                ('spots_taken', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('contact_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at', 'title'],
            },
        ),
    ]
