# Generated by Django 5.2.12 on 2026-03-24 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_demo_game_nights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenight',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_game_nights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamenight',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_game_nights', to=settings.AUTH_USER_MODEL),
        ),
    ]
